src/maimai_DX_CN_probe/views/main.py
#!/usr/bin/env/ python3
# -*- coding: utf-8 -*-
"""
    :Author: yuangezhizao-workaccount
    :Time: 2020/10/21 11:08
    :Site: https://www.yuangezhizao.cn
    :Copyright: © 2020 yuangezhizao <root@yuangezhizao.cn>
"""
import flask

from maimai_DX_CN_probe.models.maimai import HOME, PlayerData, album, Record, playlogDetail, musicInfo_2024
from maimai_DX_CN_probe.plugins.wechat_saver import save_home, save_playerData, save_playerData_album, save_record, \
    save_record_playlogDetail, save_to_aqua

app = flask.current_app
bp = flask.Blueprint('main', __name__)


@bp.route('/')
def site_index():
    return flask.render_template('index.html')


@bp.route('/wechat_archive_1.20')
def wechat_archive_1_20():
    if 'home' in flask.request.args:
        HOME_data = HOME.query.order_by(HOME.id.desc()).all()

        id_data, rating_data, rating_max_data, star_data, create_time_data = [], [], [], [], []
        for data in HOME_data:
            id_data.append(data.id)
            rating_data.append(data.rating / 100)
            rating_max_data.append(data.rating_max / 100)
            star_data.append(data.star)
            create_time_data.append(data.create_time.strftime('%Y/%m/%d %H:%M:%S'))

        return flask.render_template('maimai/wechat_archive/1.20/home.html', HOME_data=HOME_data, id_data=id_data,
                                     rating_data=rating_data, rating_max_data=rating_max_data, star_data=star_data,
                                     create_time_data=create_time_data)
    elif 'playerData' in flask.request.args:
        playerData = PlayerData.query.order_by(PlayerData.id.desc()).all()

        id_data, music_count_data, total_count_data, sssp_data, sss_data, ssp_data, ss_data, sp_data, s_data, clear_data = [], [], [], [], [], [], [], [], [], []
        app_data, ap_data, fcp_data, fc_data, fsdp_data, fsd_data, fsp_data, fs_data, create_time_data = [], [], [], [], [], [], [], [], []

        for data in playerData:
            id_data.append(data.id)
            music_count_data.append(data.music_count)
            total_count_data.append(data.total_count)

            sssp_data.append(data.sssp)
            sss_data.append(data.sss)
            ssp_data.append(data.ssp)
            ss_data.append(data.ss)
            sp_data.append(data.sp)
            s_data.append(data.s)
            clear_data.append(data.clear)

            app_data.append(data.app)
            ap_data.append(data.ap)
            fcp_data.append(data.fcp)
            fc_data.append(data.fc)
            fsdp_data.append(data.fsdp)
            fsd_data.append(data.fsd)
            fsp_data.append(data.fsp)
            fs_data.append(data.fs)
            create_time_data.append(data.create_time.strftime('%Y/%m/%d %H:%M:%S'))

        return flask.render_template('maimai/wechat_archive/1.20/playerData.html', playerData=playerData,
                                     id_data=id_data,
                                     music_count_data=music_count_data, total_count_data=total_count_data,
                                     sssp_data=sssp_data, sss_data=sss_data, ssp_data=ssp_data, ss_data=ss_data,
                                     sp_data=sp_data, s_data=s_data, clear_data=clear_data, app_data=app_data,
                                     ap_data=ap_data, fcp_data=fcp_data, fc_data=fc_data, fsdp_data=fsdp_data,
                                     fsd_data=fsd_data, fsp_data=fsp_data, fs_data=fs_data,
                                     create_time_data=create_time_data)
    elif 'playerData_album' in flask.request.args:
        playerData_album = album.query.order_by(album.id.desc()).all()
        return flask.render_template('maimai/wechat_archive/1.20/playerData_album.html',
                                     playerData_album=playerData_album)
    elif 'record' in flask.request.args:
        record_data = Record.query.order_by(Record.id.desc()).all()
        return flask.render_template('maimai/wechat_archive/1.20/record.html', record_data=record_data)
    elif 'record_playlogDetail' in flask.request.args:
        idx = int(flask.request.args.get('idx'))
        all_levels = flask.request.args.get('all_levels')
        id = idx - 1

        # 基础查询
        record_data = Record.query.get_or_404(idx)
        record_playlogDetail = playlogDetail.query.get(id)

        # 历史 record 查询
        if all_levels == '1':
            record_data_history_all = Record.query.filter_by(name=record_data.name).order_by(
                Record.id.desc()).all()
        else:
            record_data_history_all = Record.query.filter_by(name=record_data.name,
                                                             level_img_s=record_data.level_img_s).order_by(
                Record.id.desc()).all()

        # 历史 record id 提取
        id_all, record_playlogDetail_history_all = [], []
        achievement_data, delux_score_data, fc_img_s_data, fs_img_s_data, play_dt_data = [], [], [], [], []

        for record_data_history in record_data_history_all:
            id_all.append(record_data_history.id - 1)
            achievement_data.append(record_data_history.achievement)
            delux_score_data.append(record_data_history.delux_score)
            fc_img_s_data.append(100 if record_data_history.fc_img_s != 'fc_dummy' else 99)
            fs_img_s_data.append(100 if record_data_history.fs_img_s != 'fs_dummy' else 99)
            play_dt_data.append(record_data_history.play_dt.strftime('%Y-%m-%d %H:%M:%S'))

        # 历史 record_playlogDetail 查询
        for id in id_all:
            record_playlogDetail_history = playlogDetail.query.filter_by(id=id).all()[0]
            record_playlogDetail_history_all.append(record_playlogDetail_history)

        return flask.render_template('maimai/wechat_archive/1.20/record_playlogDetail.html', record_data=record_data,
                                     count=len(id_all), record_playlogDetail=record_playlogDetail,
                                     record_data_history_all=record_data_history_all,
                                     record_playlogDetail_history_all=record_playlogDetail_history_all,
                                     achievement_data=achievement_data, delux_score_data=delux_score_data,
                                     fc_img_s_data=fc_img_s_data, fs_img_s_data=fs_img_s_data,
                                     play_dt_data=play_dt_data, all_levels=all_levels)
    else:
        return flask.redirect(flask.url_for('main.wechat_archive_1_20', _external=True) + '?home')


@bp.route('/wechat_saver', methods=['GET', 'POST'])
def wechat_saver():
    auto_saver = flask.request.args.get('auto_saver')
    if auto_saver:
        if flask.request.method == 'POST':
            func_type = flask.request.form.get('func_type')
            userId = flask.request.form.get('userId')
            _t = flask.request.form.get('_t')
            if func_type == 'record_playlogDetail':
                start_posi = int(flask.request.form.get('start_posi'))
                end_posi = int(flask.request.form.get('end_posi'))
                r = save_record_playlogDetail(userId, _t, start_posi, end_posi)
                if 'ERROR' not in r[0]:
                    flask.flash(f'[详细] 存储成功：{r[0]}，Cookies：{r[1]}', 'success')
                else:
                    flask.flash(f'[详细] 存储失败：{r[0]}，Cookies：{r[1]}', 'negative')
            else:
                flask.flash(f'非法 [func_type]', 'negative')
        return flask.render_template('maimai/wechat_saver/auto.html')
    else:
        if flask.request.method == 'POST':
            html_type = flask.request.form.get('html_type')
            raw_html = flask.request.form.get('raw_html')
            if html_type == 'home':
                r = save_home(raw_html)
                flask.flash(f'[主页] 存储成功：{r}', 'success')
            elif html_type == 'playerData':
                r = save_playerData(raw_html)
                flask.flash(f'[游戏数据] 存储成功：{r}', 'success')
            elif html_type == 'playerData_album':
                r = save_playerData_album(raw_html)
                flask.flash(f'[相册] 存储成功：{r}', 'success')
            elif html_type == 'record':
                r = save_record(raw_html)
                flask.flash(f'[游戏记录] 存储成功：{r}', 'success')
            elif html_type == 'Aqua':
                r = save_to_aqua(raw_html)
                flask.flash(f'[同步 Aqua 本地服] 存储成功：{r}', 'success')
            else:
                flask.flash(f'非法 [html_type]', 'negative')
        return flask.render_template('maimai/wechat_saver/manual.html')


@bp.route('/record')
def record():
    page = int(flask.request.args.get('page', 1))
    per_page = int(flask.request.args.get('per_page', 20))
    if 'all' in flask.request.args:
        per_page = 10000
    if 'diff' in flask.request.args:
        if 'name' in flask.request.args:
            _name = flask.request.args.get('name')
            record_data_paginate = Record.query.filter_by(name=_name) \
                .order_by(Record.id.desc()) \
                .paginate(page, per_page)
        else:
            record_data_paginate = Record.query.order_by(Record.id.desc()) \
                .paginate(page, per_page)
        history_record_data = []
        record_playlogDetail_data = []
        for record_data in record_data_paginate.items:
            _id = record_data.id
            _record_playlogDetail = playlogDetail.query.get(_id - 1)

            if _record_playlogDetail and (_record_playlogDetail.notes_tap_p is not None):
                record_playlogDetail_data.append(_record_playlogDetail)
            else:
                continue

            _level_img_s = record_data.level_img_s
            _name = record_data.name
            _play_dt = record_data.play_dt
            _dx_img_s = record_data.dx_img_s
            _record_data = Record.query.filter_by(name=_name, level_img_s=_level_img_s, dx_img_s=_dx_img_s).filter(
                Record.play_dt <= _play_dt).order_by(

src/maimai_DX_CN_probe/templates/maimai/wechat_saver/auto.html
{% extends "/base.html" %}
{% from 'macros.html' import message_part with context %}

{% block title %}微信存档[自动]{% endblock %}

{% block nav %}
    <a class="active item"><i class="circle icon"></i>微信存档[自动]</a>
    <a class="item" href="{{ url_for('main.site_index') }}"><i class="arrow left icon"></i>返回首页</a>
{% endblock %}

{% block content %}
    <div class="ui dividing blue header">
        <div class="content">
            <h2>微信存档[自动]</h2>
            <div class="sub header">
                <a class="black" href="{{ url_for('main.wechat_saver') }}">切换至[手动]</a>
            </div>
        </div>
    </div>
    {{ message_part() }}
    <form class="ui form" action="{{ url_for('main.wechat_saver') }}?auto_saver=1" method="post">
        <div class="field">
            <label>Cookies</label>
            <div class="two fields">
                <div class="field">
                    <input type="text" name="userId" placeholder="userId">
                </div>
                <div class="field">
                    <input type="text" name="_t" placeholder="_t" value="f3349161266657b57ffb0b565e3eb39f">
                </div>
            </div>
        </div>
        <div class="field">
            <label>func_type</label>
            <select name="func_type" class="ui selection dropdown">
                <option value="home" disabled>home</option>
                <option value="playerData" disabled>playerData</option>
                <option value="playerData_album" disabled>playerData_album</option>
                <option value="record" disabled>record</option>
                <option value="record_playlogDetail">record_playlogDetail</option>
            </select>
        </div>
        <div class="field">
            <label>idx</label>
            <div class="two fields">
                <div class="field">
                    <input type="text" name="start_posi" maxlength="2" placeholder="0">
                </div>
                <div class="field">
                    <input type="text" name="end_posi" maxlength="2" placeholder="50">
                </div>
            </div>
        </div>
        <input class="ui positive button" type="submit" value="存储">
    </form>
{% endblock %}

src/maimai_DX_CN_probe/templates/maimai/wechat_saver/manual.html
{% extends "/base.html" %}
{% from 'macros.html' import message_part with context %}

{% block title %}微信存档[手动]{% endblock %}

{% block nav %}
    <a class="active item"><i class="circle icon"></i>微信存档[手动]</a>
    <a class="item" href="{{ url_for('main.site_index') }}"><i class="arrow left icon"></i>返回首页</a>
{% endblock %}

{% block content %}
    <div class="ui dividing blue header">
        <div class="content">
            <h2>微信存档[手动]</h2>
            <div class="sub header">
                <a href="{{ url_for('main.wechat_saver') }}?auto_saver=1">切换至[自动]</a>
            </div>
        </div>
    </div>
    {{ message_part() }}
    <form class="ui form" action="{{ url_for('main.wechat_saver') }}" method="post">
        <div class="field">
            <label>html_type</label>
            <select name="html_type" class="ui selection dropdown">
                <option value="home">home</option>
                <option value="playerData">playerData</option>
                <option value="playerData_album">playerData_album</option>
                <option value="record">record</option>
                <option value="record_playlogDetail" disabled>record_playlogDetail</option>
                <option value="Aqua">同步 Aqua 本地服</option>
            </select>
        </div>
        <div class="field">
            <label>raw_html</label>
            <textarea name="raw_html" rows="5" placeholder="输入原始网页" autofocus></textarea>
        </div>
        <input class="ui positive button" type="submit" value="存储">
    </form>
{% endblock %}