src/maimai_DX_CN_probe/views/main.py
#!/usr/bin/env/ python3
# -*- coding: utf-8 -*-
"""
    :Author: yuangezhizao-workaccount
    :Time: 2020/10/21 11:08
    :Site: https://www.yuangezhizao.cn
    :Copyright: © 2020 yuangezhizao <root@yuangezhizao.cn>
"""
import flask

from maimai_DX_CN_probe.models.maimai import HOME, PlayerData, album, Record, playlogDetail, musicInfo_2024
from maimai_DX_CN_probe.plugins.wechat_saver import save_home, save_playerData, save_playerData_album, save_record, \
    save_record_playlogDetail, save_to_aqua

app = flask.current_app
bp = flask.Blueprint('main', __name__)


@bp.route('/')
def site_index():
    return flask.render_template('index.html')


@bp.route('/wechat_archive_1.20')
def wechat_archive_1_20():
    if 'home' in flask.request.args:
        HOME_data = HOME.query.order_by(HOME.id.desc()).all()

        id_data, rating_data, rating_max_data, star_data, create_time_data = [], [], [], [], []
        for data in HOME_data:
            id_data.append(data.id)
            rating_data.append(data.rating / 100)
            rating_max_data.append(data.rating_max / 100)
            star_data.append(data.star)
            create_time_data.append(data.create_time.strftime('%Y/%m/%d %H:%M:%S'))

        return flask.render_template('maimai/wechat_archive/1.20/home.html', HOME_data=HOME_data, id_data=id_data,
                                     rating_data=rating_data, rating_max_data=rating_max_data, star_data=star_data,
                                     create_time_data=create_time_data)
    elif 'playerData' in flask.request.args:
        playerData = PlayerData.query.order_by(PlayerData.id.desc()).all()

        id_data, music_count_data, total_count_data, sssp_data, sss_data, ssp_data, ss_data, sp_data, s_data, clear_data = [], [], [], [], [], [], [], [], [], []
        app_data, ap_data, fcp_data, fc_data, fsdp_data, fsd_data, fsp_data, fs_data, create_time_data = [], [], [], [], [], [], [], [], []

        for data in playerData:
            id_data.append(data.id)
            music_count_data.append(data.music_count)
            total_count_data.append(data.total_count)

            sssp_data.append(data.sssp)
            sss_data.append(data.sss)
            ssp_data.append(data.ssp)
            ss_data.append(data.ss)
            sp_data.append(data.sp)
            s_data.append(data.s)
            clear_data.append(data.clear)

            app_data.append(data.app)
            ap_data.append(data.ap)
            fcp_data.append(data.fcp)
            fc_data.append(data.fc)
            fsdp_data.append(data.fsdp)
            fsd_data.append(data.fsd)
            fsp_data.append(data.fsp)
            fs_data.append(data.fs)
            create_time_data.append(data.create_time.strftime('%Y/%m/%d %H:%M:%S'))

        return flask.render_template('maimai/wechat_archive/1.20/playerData.html', playerData=playerData,
                                     id_data=id_data,
                                     music_count_data=music_count_data, total_count_data=total_count_data,
                                     sssp_data=sssp_data, sss_data=sss_data, ssp_data=ssp_data, ss_data=ss_data,
                                     sp_data=sp_data, s_data=s_data, clear_data=clear_data, app_data=app_data,
                                     ap_data=ap_data, fcp_data=fcp_data, fc_data=fc_data, fsdp_data=fsdp_data,
                                     fsd_data=fsd_data, fsp_data=fsp_data, fs_data=fs_data,
                                     create_time_data=create_time_data)
    elif 'playerData_album' in flask.request.args:
        playerData_album = album.query.order_by(album.id.desc()).all()
        return flask.render_template('maimai/wechat_archive/1.20/playerData_album.html',
                                     playerData_album=playerData_album)
    elif 'record' in flask.request.args:
        record_data = Record.query.order_by(Record.id.desc()).all()
        return flask.render_template('maimai/wechat_archive/1.20/record.html', record_data=record_data)
    elif 'record_playlogDetail' in flask.request.args:
        idx = int(flask.request.args.get('idx'))
        all_levels = flask.request.args.get('all_levels')
        id = idx - 1

        # 基础查询
        record_data = Record.query.get_or_404(idx)
        record_playlogDetail = playlogDetail.query.get(id)

        # 历史 record 查询
        if all_levels == '1':
            record_data_history_all = Record.query.filter_by(name=record_data.name).order_by(
                Record.id.desc()).all()
        else:
            record_data_history_all = Record.query.filter_by(name=record_data.name,
                                                             level_img_s=record_data.level_img_s).order_by(
                Record.id.desc()).all()

        # 历史 record id 提取
        id_all, record_playlogDetail_history_all = [], []
        achievement_data, delux_score_data, fc_img_s_data, fs_img_s_data, play_dt_data = [], [], [], [], []

        for record_data_history in record_data_history_all:
            id_all.append(record_data_history.id - 1)
            achievement_data.append(record_data_history.achievement)
            delux_score_data.append(record_data_history.delux_score)
            fc_img_s_data.append(100 if record_data_history.fc_img_s != 'fc_dummy' else 99)
            fs_img_s_data.append(100 if record_data_history.fs_img_s != 'fs_dummy' else 99)
            play_dt_data.append(record_data_history.play_dt.strftime('%Y-%m-%d %H:%M:%S'))

        # 历史 record_playlogDetail 查询
        for id in id_all:
            record_playlogDetail_history = playlogDetail.query.filter_by(id=id).all()[0]
            record_playlogDetail_history_all.append(record_playlogDetail_history)

        return flask.render_template('maimai/wechat_archive/1.20/record_playlogDetail.html', record_data=record_data,
                                     count=len(id_all), record_playlogDetail=record_playlogDetail,
                                     record_data_history_all=record_data_history_all,
                                     record_playlogDetail_history_all=record_playlogDetail_history_all,
                                     achievement_data=achievement_data, delux_score_data=delux_score_data,
                                     fc_img_s_data=fc_img_s_data, fs_img_s_data=fs_img_s_data,
                                     play_dt_data=play_dt_data, all_levels=all_levels)
    else:
        return flask.redirect(flask.url_for('main.wechat_archive_1_20', _external=True) + '?home')


@bp.route('/wechat_saver', methods=['GET', 'POST'])
def wechat_saver():
    auto_saver = flask.request.args.get('auto_saver')
    if auto_saver:
        if flask.request.method == 'POST':
            func_type = flask.request.form.get('func_type')
            userId = flask.request.form.get('userId')
            _t = flask.request.form.get('_t')
            if func_type == 'record_playlogDetail':
                start_posi = int(flask.request.form.get('start_posi'))
                end_posi = int(flask.request.form.get('end_posi'))
                r = save_record_playlogDetail(userId, _t, start_posi, end_posi)
                if 'ERROR' not in r[0]:
                    flask.flash(f'[详细] 存储成功：{r[0]}，Cookies：{r[1]}', 'success')
                else:
                    flask.flash(f'[详细] 存储失败：{r[0]}，Cookies：{r[1]}', 'negative')
            else:
                flask.flash(f'非法 [func_type]', 'negative')
        return flask.render_template('maimai/wechat_saver/auto.html')
    else:
        if flask.request.method == 'POST':
            html_type = flask.request.form.get('html_type')
            raw_html = flask.request.form.get('raw_html')
            if html_type == 'home':
                r = save_home(raw_html)
                flask.flash(f'[主页] 存储成功：{r}', 'success')
            elif html_type == 'playerData':
                r = save_playerData(raw_html)
                flask.flash(f'[游戏数据] 存储成功：{r}', 'success')
            elif html_type == 'playerData_album':
                r = save_playerData_album(raw_html)
                flask.flash(f'[相册] 存储成功：{r}', 'success')
            elif html_type == 'record':
                r = save_record(raw_html)
                flask.flash(f'[游戏记录] 存储成功：{r}', 'success')
            elif html_type == 'Aqua':
                r = save_to_aqua(raw_html)
                flask.flash(f'[同步 Aqua 本地服] 存储成功：{r}', 'success')
            else:
                flask.flash(f'非法 [html_type]', 'negative')
        return flask.render_template('maimai/wechat_saver/manual.html')


@bp.route('/record')
def record():
    page = int(flask.request.args.get('page', 1))
    per_page = int(flask.request.args.get('per_page', 20))
    if 'all' in flask.request.args:
        per_page = 10000
    if 'diff' in flask.request.args:
        if 'name' in flask.request.args:
            _name = flask.request.args.get('name')
            record_data_paginate = Record.query.filter_by(name=_name) \
                .order_by(Record.id.desc()) \
                .paginate(page, per_page)
        else:
            record_data_paginate = Record.query.order_by(Record.id.desc()) \
                .paginate(page, per_page)
        history_record_data = []
        record_playlogDetail_data = []
        for record_data in record_data_paginate.items:
            _id = record_data.id
            _record_playlogDetail = playlogDetail.query.get(_id - 1)

            if _record_playlogDetail and (_record_playlogDetail.notes_tap_p is not None):
                record_playlogDetail_data.append(_record_playlogDetail)
            else:
                continue

            _level_img_s = record_data.level_img_s
            _name = record_data.name
            _play_dt = record_data.play_dt
            _dx_img_s = record_data.dx_img_s
            _record_data = Record.query.filter_by(name=_name, level_img_s=_level_img_s, dx_img_s=_dx_img_s).filter(
                Record.play_dt <= _play_dt).order_by(

src/maimai_DX_CN_probe/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="keywords" content="maimai 查分器,maimai DX 查分器,舞萌 DX 查分器,maimai,maimai_DX,舞萌DX,yuangezhizao"/>
    <meta name="description" content="这里是个人在用的 maimai_DX 查分器">
    <meta name="author" content="yuangezhizao"/>
    <meta name="Copyright" content="Copyright yuangezhizao All Rights Reserved."/>
    <meta name="format-detection" content="telephone=no"/>
    <link rel="stylesheet" type="text/css" href="https://s1.yuangezhizao.cn/npm/fomantic-ui/dist/semantic.min.css">
    <link rel="dns-prefetch" href="//maimai.yuangezhizao.cn">
    <link rel="dns-prefetch" href="//lab.yuangezhizao.cn">
    <link rel="dns-prefetch" href="//www.yuangezhizao.cn">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=yes">
    {% block head %}{% endblock %}
</head>
<body>
{% block body %}
    <div class="ui container">
        <div class="ui blue pointing menu">
            {% block nav %}
                <a class="active item"><i class="home icon"></i>首页</a>
                <a class="item" href="https://github.com/yuangezhizao/maimai_DX_CN_probe" target="_blank"><i
                        class="archive icon"></i>源码</a>
            {% endblock %}
        </div>
        {% block content %}{% endblock %}
        <div class="ui divider"></div>
        <footer>
            <div class="ui info message" style="text-align: center;">
                yuangezhizao&nbsp&nbsp&nbsp&nbsp©&nbsp&nbsp&nbsp&nbsp2020 - 2025<br>
                Powered by Railway
            </div>
        </footer>
    </div>
{% endblock %}
<script src="https://s1.yuangezhizao.cn/npm/jquery/dist/jquery.min.js"></script>
<script src="https://s1.yuangezhizao.cn/npm/fomantic-ui/dist/semantic.min.js"></script>
<script>
    $('.message .close').on('click', function () {
        $(this).closest('.message').transition('fade');
    });
    $('.selection.dropdown')
        .dropdown()
    ;
</script>
{% block script %}{% endblock %}
<script async defer data-website-id="89b8d7c1-3746-47ce-86ed-8c3e51fd92c0" src="https://umami.yuangezhizao.cn/mikecao.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-65GFJD0XP7"></script>
<script defer src='https://hm.baidu.com/hm.js?52627b664e5a3d9647f8361d409caf63'></script>
<script src="https://cdn-go.cn/aegis/aegis-sdk/latest/aegis.min.js"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());
    gtag('config', 'G-65GFJD0XP7');
    var _hmt = _hmt || [];
    const aegis = new Aegis({
        id: 'DvV9gCEQd4zkz3101P', // 上报 id
        uin: 'Anonymous', // 用户唯一 ID（可选）
        reportApiSpeed: true, // 接口测速
        reportAssetSpeed: true, // 静态资源测速
        spa: true // spa 应用页面跳转的时候开启 pv 计算
    });
</script>
</body>
</html>

src/maimai_DX_CN_probe/templates/index.html
{% extends "/base.html" %}

{% block title %}maimai_DX 查分器{% endblock %}

{% block content %}
    <div class="ui positive message">
        <h2 class="ui header">欢迎访问 ヽ(･ω･´ﾒ)</h2>
        <p>这里是个人在用的 maimai_DX 查分器，<a
                href="https://www.yuangezhizao.cn/articles/python/flask/serverless/maimai_DX_CN_probe.html">查看简介</a>
        </p>
    </div>

    <h4 class="ui top attached block green header">
        wechat_archive
    </h4>
    <div class="ui bottom attached green segment">
        <a href="{{ url_for('main.wechat_archive_1_20') + '?home' }}">主页</a>，
        <a href="{{ url_for('main.wechat_archive_1_20') + '?playerData' }}">游戏数据</a>，
        <a href="{{ url_for('main.wechat_archive_1_20') + '?playerData_album' }}">相册</a>，
        <a href="{{ url_for('main.wechat_archive_1_20') + '?record' }}">游戏记录</a>
    </div>

    <h4 class="ui top attached block purple header">
        record
    </h4>
    <div class="ui attached purple segment">
        <a href="{{ url_for('main.record') }}">记录（分页）</a>，
        <a href="{{ url_for('main.record') + '?diff' }}">差异（分页）</a>
    </div>
    <div class="ui bottom attached segment">
        <a href="{{ url_for('main.record') + '?all' }}">记录（全部）</a>，
        <a href="{{ url_for('main.record')+ '?diff&all' }}">差异（全部）</a>
    </div>

    <h4 class="ui top attached block brown header">
        info
    </h4>
    <div class="ui bottom attached brown segment">
        <a href="{{ url_for('main.info') }}">铺面列表（Ver.CN1.41-I）</a>
    </div>

    <h4 class="ui top attached block pink header">
        rating
    </h4>
    <div class="ui bottom attached pink segment">
        <a href="{{ url_for('main.rating') }}" style="pointer-events:none">得分计算（定数表维护）</a>
    </div>

    <h4 class="ui top attached block orange header">
        maimai_DX_CN_saver
    </h4>
    <div class="ui bottom attached orange segment">
        <a href="https://github.com/yuangezhizao/maimai_DX_CN_saver" target="_blank">数据存储</a>
    </div>
{% endblock %}